### ISSUE TITLE
Fatal Error on install

### ISSUE THREAD

**Issue by ArthurJGuy** [ericwindham/ninja-forms-bulk-submissions-delete#1]
After installation I'm getting an error on the plugins page.

"Fatal error: Class 'NF_Bulk_Submission_Delete_Admin_Menus_BulkSubmissionDelete' not found in /srv/users/serverpilot/apps/email-gateway/public/wp-content/plugins/ninja-forms-bulk-submissions-delete/ninja-forms-bulk-submission-delete.php on line 108"

I am using NF 3.2.10, and would be glad to help troubleshoot.

Thanks.

**Comment by ericwindham** [comment]
Hi Arthur

Can you tell me if you installed the master branch or the develop branch?

**Comment by ArthurJGuy** [comment]
I tried it with both branches and got the same result.

**Comment by ericwindham** [comment]
Interesting. I tried both branches and didn't have any issues. 

I built this for a customer that had several thousand submissions so they might delete them without too much cpu usage.

There were some issues with

**Comment by ericwindham** [comment]
try this. Rename the file 'includes/Admin/Menus/bulkSubmissionDelete.php' to BulkSubmissionDelete.php

And let me know.

**Comment by ArthurJGuy** [comment]
I renamed the file and activated the plugin, this is the error message I received.

Fatal error: Class 'NF_BulkSubmissionDelete_Ajax_Controllers_BulkDelete' not found in /srv/users/serverpilot/apps/email-gateway/public/wp-content/plugins/ninja-forms-bulk-submissions-delete/ninja-forms-bulk-submission-delete.php on line 119

**Comment by ArthurJGuy** [comment]
It appears to be a different error at least.

**Comment by ericwindham** [comment]
Now rename the file 'includes/AJAX/Controllers/bulkDelete.php' to 'BulkDelete.php'

**Comment by ArthurJGuy** [comment]
Negative, same error as before.

**Comment by ericwindham** [comment]
On line 119 in 'srv/users/serverpilot/apps/email-gateway/public/wp-content/plugins/ninja-forms-bulk-submissions-delete/ninja-forms-bulk-submission-delete.php' change the code from:

NF_BulkSubmissionDelete_Ajax_Controllers_BulkDelete();

to:

NF_BulkSubmissionDelete_AJAX_Controllers_BulkDelete();

**Comment by ArthurJGuy** [comment]
That worked, I got it activated.   Thanks!

**Comment by ericwindham** [comment]
NP, that's just sloppy on my part. I work for Ninja Form and had a customer that had 10s of thousands of submissions and deleting them all was too time consuming, so I built this little step processor to do it. I just troubleshot locally and ended up editing the files on their site via FTP to.

Most *nix servers are ambiguous about capitalization, but some aren't. I'll leave this open until I can get the develop and master branches updated.

**Comment by ArthurJGuy** [comment]
That's exactly my scenario, we use NF as a email gateway to access the public WiFi at our Hotel & Casino, so I get roughly 10k-15k submissions a day.    There used to be a button to empty the form but when I upgraded to 3.0 it went away.     I like to download them every week and clean the DB out, so the server stays happy.     I'd love to see this built in to 3.x it's a very valuable feature.

Thanks again for your help.

**Comment by ericwindham** [comment]
Closing this issue since I've updated the repo with fixes.
